version : '3.7'
services :
  api :
    build : '.'
    container_name : 'api'
    environment :
      PORT : 1337
      DB_URI : 'mongodb://dev:goofy@mongodb?directConnection=true&serverSelectionTimeoutMS=2000'
    networks :
      back : {}
    ports :
      - target :  1337
        published : 1337
        protocol : 'tcp'
    volumes :
      - source : '.'
        target : '/home/node/app'
        type : 'bind'
      - './dist:/app/dist'
      - './node_modules:/app/node_modules'
      - './coverage:/app/coverage'
    tty : true
  mongodb :
    container_name : 'mongodb'
    environment:
      MONGO_INITDB_ROOT_USERNAME : 'dev'
      MONGO_INITDB_ROOT_PASSWORD : 'goofy'
    image : 'mongo'
    networks :
      back : {}
    ports :
      - 27017
networks :
  back :
    driver : 'bridge'
    attachable : true
